/*
THREE TYPES OF EXPRESSIONS : 

1 . INFIX EXPRESSIONS :  SYNTAX : OPERAND OPERATOR OPERAND 

EG : 4 + 2 , 4 * 5 + 6

PRECEDENCE OF OPERATORS : 
1 ()
2 ^      (R -> L)
3 * , /  (L -> R)
4 + , -  (L -> R)

2 . PREFIX EXPRESSION (Polish Expression) : SYNTAX : OPERATOR OPERAND OPERAND

EG : ((4 * 5) + 6)  => + * 4 5 6

TO CONVERT PREFIX TO INFIX WE ITERATE FROM BACK AND AS SOON AS WE SEE AN OPERATOR
WE PERFORM IT ON THE LAST 2 OPERATOR INSERTED INTO THE STACK.

AND WE KNOW THAT IN AN PREFIX EXPRESSION , THE LESS PRECEDENCE OPERATOR COMES 
TOWARDS LEFT SIDE. 

3 . POSTFIX EXPRESSION (REVERSE POLISH EXPRESSION) : SYNTAX : OPERATOR OPERATOR OPERAND.

EG : ((4 * 2) + 3) => 4 2 * 3 +
EG : (5 - (6 / 3)) => 5 6 3 / -

TO CONVERT TO POSTFIX TO INFIX , WE ITERATE FROM THE FRONT AND WHENEVER WE SEE AN OPERATOR
WE PERFORM IT ON THE LAST 2 OPERANDS.


*/
